FROM python:3.11-slim

WORKDIR /app

COPY requirements_ocr.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY api_ocr.py /app/api_ocr.py

EXPOSE 5000

CMD ["uvicorn", "api_ocr:app", "--host", "0.0.0.0", "--port", "5000"]