FROM python:3.11-slim

COPY ./ner-api/requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Copy the app.py file
COPY ./ner-api/app.py /app.py

# Expose 8000 for uvicorn
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]